export default {
  CREATE_COURSE: "CREATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",
  UDPATE_COURSE: "UDPATE_COURSE",
  CREATE_AUTHOR: "CREATE_AUTHOR",
  DELETE_AUTHOR: "DELETE_AUTHOR",
  LOAD_AUTHORS: "LOAD_AUTHORS",
};
